apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "node-todo.fullname" . }}-allow-nginx
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "node-todo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}