apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-todo.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "node-todo.name" . }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}